backend:
  name: github
  repo: Axiomatic47/corporate-veil
  branch: main
  # Remove or comment out the base_url if not using a custom GitHub Enterprise instance
  # base_url: http://localhost:8081

# Disable local_backend unless you have a local backend server running
# Comment out or set to false if not needed
# local_backend: true
# local_backend_url: http://localhost:8082

media_folder: "public/uploads"
public_folder: "/uploads"
format: "json"

editor:
  preview: false

collections:
  - name: "compositions"
    label: "Compositions"
    folder: "content/compositions"
    create: true
    extension: "json"
    slug: "{{collection_type}}-{{slug}}"
    preview_path: "composition/{{collection_type}}/section/1"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "collection_type", widget: "select", options: ["memorandum", "corrective"]}
      - label: "Sections"
        name: "sections"
        widget: "list"
        allow_add: true
        label_singular: "Section"
        summary: "{{fields.title}}"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Featured on Homepage", name: "featured", widget: "boolean", default: false, required: false}
          - label: "Basic Content (Level 1)"
            name: "content_level_1"
            widget: "markdown"
            required: false
            hint: "Optional - will default to intermediate content if left blank"
            editor_components: ["bold", "italic", "link", "bulleted-list", "numbered-list", "quote"]
            modes: ["rich_text", "raw"]
            buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list", "quote"]
            sanitize_preview: false
          - label: "Intermediate Content (Level 3)"
            name: "content_level_3"
            widget: "markdown"
            required: true
            editor_components: ["bold", "italic", "link", "bulleted-list", "numbered-list", "quote"]
            modes: ["rich_text", "raw"]
            buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list", "quote"]
            sanitize_preview: false
          - label: "Advanced Content (Level 5)"
            name: "content_level_5"
            widget: "markdown"
            required: false
            hint: "Optional - will default to intermediate content if left blank"
            editor_components: ["bold", "italic", "link", "bulleted-list", "numbered-list", "quote"]
            modes: ["rich_text", "raw"]
            buttons: ["bold", "italic", "link", "bulleted-list", "numbered-list", "quote"]
            sanitize_preview: false
