backend:
  name: test-repo
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: placeholder
    label: Placeholder
    files:
      - name: placeholder
        label: Placeholder
        file: "content/placeholder.md"
        fields:
          - {label: Title, name: title, widget: string}